---
- name: Install Instana Agent via setup_agent.sh (IAIM Embedded)
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes

  vars:
    # Default values (สามารถ override ผ่าน Catalog dialog)
    instana_agent_key: "{{ dialog_instana_agent_key | default('hQUUlC0qF9BP8yEu98H59H') }}"
    instana_agent_name: "{{ dialog_instana_agent_name | default('KlCtr5DRRFR4YrWtj9Yimw') }}"
    instana_agent_host: "{{ dialog_instana_agent_host | default('10.200.124.235:1444') }}"
    agent_type: "{{ dialog_agent_type | default('dynamic') }}"
    setup_script_path: /tmp/setup_agent.sh

  tasks:

    - name: Download Instana setup script
      get_url:
        url: https://setup.instana.io/agent
        dest: "{{ setup_script_path }}"
        mode: '0700'

    - name: Run Instana Agent setup script
      command: >
        {{ setup_script_path }}
        -a {{ instana_agent_key }}
        -d {{ instana_agent_name }}
        -t {{ agent_type }}
        -e {{ instana_agent_host }}
      become: yes
      register: agent_install
      ignore_errors: no

    - name: Show installation result
      debug:
        msg: "{{ agent_install.stdout }}"
